print(' "Hello,world" ')
print("Hello \" world")
print ('\Hi')
print('\\')
print(2+3)
print('2+3')
print('Hello, ' + "Adil")
print('Hello,', "Adil", 'and Aibar')
print('Hello,', "Adil", "and Aibar", sep="LOL")
print("Hello \n Adil")
print("Hello \nAdil")

print("Я прохожу курс по Python \nI'm studiyng Python with course 'programming on Python from zero to master'")
print("I laughed when he said 'OMG that shit had to happen' \nBut that was anapropriate")
